### ISSUE TITLE
feature:API 연동

### ISSUE THREAD

**Issue by zxcv2987** [team-culfare/Mbti-Lens#38]
### 📄 Description
_API 연동

### ✅ Tasks
- [x] _Fetching 방식 정하기
- [x]  data posting test
- [ ]  post완료 시 행동 처리하기 => 완료페이지로 이동해서 나도해보기 버튼으로 유도한다던지
