### ISSUE TITLE
feature:댓글 확인, 등록시 public_key확인

### ISSUE THREAD

**Issue by woomae** [team-culfare/Mbti-Lens#40]
### 📄 Description
_댓글 등록시 public_key를 확인하는 기능을 추가한다_

### ✅ Tasks
- [x] _Post방식 또는 Get방식으로 댓글 등록 및 조회시 public_key확인 기능 추가._
- [x] _merge후 명세서 수정 필요!_
- [x] _서버에 users테이블 수정_
