### ISSUE TITLE
feature:mbti평가 시 Post 방식 수정

### ISSUE THREAD

**Issue by woomae** [team-culfare/Mbti-Lens#67]
### 📄 Description
_기존의 한번씩 요청하여 값을 받아오지 않고 한번에 받아서 처리_
_좋아요 수 업데이트 방식 변경(생성 후 db에 좋아요 row값 조회 --> 좋아요 수만 다른 테이블에 +1)_

### ✅ Tasks
- [x] _값 한번에 받아 처리하기_
- [x] _comment 미입력시 테이블에 저장하지 않도록 수정_
- [x] _댓글 생성시 좋아요 수를 확인 하는 테이블에 값 수정_
- [x] _명세서 수정_
- [x] _서버에 pull_
